name: Licensed

on:
  push:
    branches:
      - main
      - populate-reusable-workflows
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  licenced:
    uses: IvanZosimov/reusable-workflows/.github/workflows/licensed.yml@main
