name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  licenced:
    uses: IvanZosimov/reusable-workflows/.github/workflows/licensed.yml@main
    with:
      licensed-url: "https://github.com/github/licensed/releases/download/3.9.0/licensed-3.9.0-linux-x64.tar.gz"
