name: Main workflow

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      enable-audit:
        required: true
        type: boolean
        default: false

jobs:
  ci:
    uses: IvanZosimov/reusable-workflows/.github/workflows/basic-validation.yml@main
    with:
      operating-systems: "['ubuntu-latest']"
      enable-audit: true
      node-version: "18.x"
      node-caching: ""
