name: Main workflow

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
      - populate-reusable-workflows
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  ci:
    uses: IvanZosimov/reusable-workflows/.github/workflows/basic-validation.yml@main
